### PR TITLE
Add change default password length setting

### LINKED ISSUE #594: Change password length default value
When you generate passwords you can change the length of the password but it reverts back to 10 after you go out of the menu, I would like it to stay to what I changed instead of changing back to 10(or at least option in the settings to decide the default to another number)

### PR DESCRIPTION
**Pull request by vladleesi**
closed #594 

| Settings | Screen |
|----------|----------|
| Screenshot_1685660676 | Screenshot_1685660678 |

### CODE REVIEW

**Comment by yogeshpaliyal** [comment]
@vladleesi thanks for the PR, there is a little suggestion, can we save the password length from generate password settings itself instead of creating a new settings page.

**Comment by vladleesi** [comment]
@yogeshpaliyal I thought about it, technically there is no difficulty, we can save when exiting the password generation screen, but it seems to me that this may not be obvious to the user.

**Comment by yogeshpaliyal** [comment]
@vladleesi Can we save on both the password length changes in same shared prefs.

**Comment by vladleesi** [comment]
@yogeshpaliyal No problem, we can save in two places. But I liked the option of saving after generation, Bitwarden has a similar logic. Give me some time)

**Comment by yogeshpaliyal** [comment]
sure, take your time

**Comment by vladleesi** [comment]
done

**Review by yogeshpaliyal — APPROVED** [review]

**Comment by yogeshpaliyal** [comment]
Thanks @vladleesi for this valuable contribution ❤️  🚀

**Pull request merged**
