### PR TITLE
Generate a QR code to export all account details as JSON

### PR DESCRIPTION
**Pull request by divyampahujaa**
This pull request addresses issue #559.  

Export button:
image

QR code: 
image

JSON output:
image

### CODE REVIEW

**Comment by yogeshpaliyal** [comment]
The export button can be at the bottom with the back and delete buttons, also we can open the QR code on another screen where we can give the option to download the QR code

**Comment by divyampahujaa** [comment]
Sure, that sounds good. I will make the changes accordingly.

**Comment by divyampahujaa** [comment]
@yogeshpaliyal I have changed the feature like you suggested. Please have a look :)

Export button on bottom nav bar:
image

Generated QR code in a popup screen:
image

Ability to save the QR code to gallery:
image

**Review by yogeshpaliyal — DISMISSED** [review]
LGTM

**Comment by divyampahujaa** [comment]
Thank you for approving my PR! However, I notice the PR check CI pipeline has failed and the changes were not merged due to the use of deprecated gradle features. I haven't changed any build scripts though. How can we fix this?

**Comment by yogeshpaliyal** [comment]
@divyampahujaa checks failed due to spotless
Please run these command
./gradlew spotlessApply
./gradle spotlessKotlinApply

**Comment by divyampahujaa** [comment]
@yogeshpaliyal I ran those commands. The issue was with using wildcard imports. I have changed the imports to address this.

**Comment by yogeshpaliyal** [comment]
Cool thanks

**Review by yogeshpaliyal — APPROVED** [review]

**Comment by yogeshpaliyal** [comment]
Pr Merged thanks @divyampahujaa for the contribution ❤️, will look for other contribution.

**Pull request merged**
