### PR TITLE
Issue #477 Multiple setting page issue resolved

### PR DESCRIPTION
**Pull request by rohitashwani1**

### CODE REVIEW

**Comment by yogeshpaliyal** [comment]
@rohitashwani1 can you please attach a video too

**Comment by yogeshpaliyal** [comment]
@rohitashwani1 please fix the formatting issue too by running `./gradlew :app:spotlessApply`

**Comment by rohitashwani1** [comment]
I have updated the code and tried running "./gradlew :app:spotlessApply" and build is successful and the app is showing the expected behaviour.

commit cd0a9af0bf4fa6ffb197d9d999afe96fa9206430 is the updated one.

**Comment by yogeshpaliyal** [comment]
Thanks @rohitashwani1 ♥️

**Pull request merged**
