### PR TITLE
Add Password Generator with Specific Special Characters #862

### PR DESCRIPTION
**Pull request by kapilBaser**
**Changes:**
1. Added one more variable in PasswordConfig called listOfSymbols to ensure which symbols the user selects.
2. I added FlowRow in the UI after the symbol checkbox.
3. SelectSymbolForPassword (symbol: Char) was added to update the passwordConfig.listOfSymbols in GeneratePasswordViewModel.

### CODE REVIEW

**Comment by yogeshpaliyal** [comment]
@kapilBaser can you please add a screenshot and video for the flow

**Comment by kapilBaser** [comment]
### Screenshot


### Video
https://github.com/yogeshpaliyal/KeyPass/assets/94954247/8ad34c4a-5323-4279-8d92-6b80f29ccea5

**Comment by yogeshpaliyal** [comment]
@kapilBaser can you please check spotless issues

**Comment by yogeshpaliyal** [comment]
@kapilBaser can we add select symbols to passwordConfig so it will be saved to preference and will be auto selected next time and the same config will be used in password generation while adding new account.

**Comment by kapilBaser** [comment]
In the current version of the app, we've added a feature where users can select specific symbols for password generation. These selections are saved in a listOfSymbols within the password configuration. Even if the activity is destroyed, the selected symbols are preserved because the PasswordConfig object is stored in userSetting. 
I'm right?

**Comment by yogeshpaliyal** [comment]
@kapilBaser yes, Correct

**Comment by kapilBaser** [comment]
So, Is there some more addition you want?

**Comment by yogeshpaliyal** [comment]
My bad, PR looks good will merge after checks pass

**Comment by yogeshpaliyal** [comment]
@kapilBaser 
You can run command 
./gradlew spotlessApply 
./gradlew spotlessKotlinApply

**Comment by kapilBaser** [comment]
Done!

**Comment by yogeshpaliyal** [comment]
Thank you @kapilBaser for your Invaluable contribution ♥️

**Comment by kapilBaser** [comment]
It's my pleasure @yogeshpaliyal ! This is my first contribution to open source, and I'm excited to make more PRs in the future. 😊

**Pull request merged**
